name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Debug APK
        run: ./gradlew clean assembleDebug --stacktrace

      - name: List APKs
        run: ls -R app/build/outputs/apk || true

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: GreenValley-debug-apk
          path: app/build/outputs/apk/debug/*.apk
