name: Android Debug APK

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: List repo structure
        run: |
          echo "### Root contents:"
          ls -R .

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Build Debug APK
        run: ./gradlew clean :app:assembleDebug --stacktrace

      - name: List APK directory
        run: ls -R app/build/outputs/apk || true

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: GreenValley-debug-apk
          path: app/build/outputs/apk/debug/*.apk
